version: "3.8"

services:
  node:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'hgfnfgh sdfsdfds sdfsdf sdfsdf ASSa 22asdas asdysd2 sadas jhbasdhn2n asdasdsaasdads8s 8s 8 dsa8as d8 ads88 sad8as 8as 889 as 2121 !" !"" ! QWERas#+asd+asd+d.asd ,,wad... y><<< 2ojkjok v2 jkasdasdd 22 2 2 2kj a sdasdadskdas kjdsa adfshadsf asdf kasfasfjkasfasf askj sdkads fui14h123124412 1240 122 1ASD ads dsd asdasadsasdasdasdadsdsadsfasfasff aa saf djhafs fasasfafs fsa af safsasfjklasfklafs 21123 12ojk mklööl,fas v da#äö aslsa +as f asß0p21 12)=)  22 2 2 1A SD21 § !ADSF ASDAS F-ALDF ÖSADFk adfs+a sdfadsf 46 26512 3r1 qlöewka xc aadsöas dsd'
      - --networkId
      - "1337"
      - --debug
      - --acctKeys
      - "keys.json"
      - -a
      - "100"
      - -l
      - "67219750"
      - --hostname
      - "0.0.0.0"
      - --debug

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lucidadmin
      - POSTGRES_PASSWORD=projekt1234
      - POSTGRES_DB=luciddb

  react-ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

volumes:
  postgres_data:
# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]



