# Generated by Django 4.0.1 on 2022-07-17 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('eori_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=60)),
                ('city_code', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('publickey', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomsOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=60)),
                ('city_code', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('publickey', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=345)),
                ('blockchain_id', models.CharField(blank=True, max_length=30)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('issue_date', models.DateField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_processed', models.DateTimeField(auto_now=True)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner1', to='lucidapp.company')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner2', to='lucidapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=300)),
                ('tariccode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('tax_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lucidapp.document')),
                ('invoice_text', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transport_costs', models.FloatField(default=0)),
            ],
            bases=('lucidapp.document',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_processed', models.DateField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_processed', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Transaktion wurde angelegt - Bestätigung ausstehend'), (2, 'Alle Dokumente liegen vor'), (3, 'Zollantrag gestellt - Wartet auf Bearbeitung'), (4, 'Zollfreigabe durch Zollamt erteilt')], default=1)),
                ('importeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lucidapp.company')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnership', to='lucidapp.partnership')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='lucidapp.company')),
                ('custom_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_officers', to='lucidapp.customsoffice')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lucidapp.file'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='lucidapp.transaction'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=90)),
                ('unit', models.CharField(max_length=90)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceItem', to='lucidapp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('blockchain_zid', models.CharField(default='', max_length=400)),
                ('anmeldeArt', models.CharField(max_length=400)),
                ('geschaeftArt', models.CharField(max_length=300)),
                ('zahlungsart', models.CharField(blank=True, max_length=400)),
                ('ausfuhrland', models.CharField(max_length=100)),
                ('bestimmungsland', models.CharField(max_length=100)),
                ('befoerderungsmittel', models.CharField(max_length=100)),
                ('lieferbedingung', models.CharField(max_length=100)),
                ('lieferort', models.CharField(max_length=100)),
                ('warenort', models.CharField(blank=True, max_length=100)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('status_verificiation', models.CharField(default='ausstehend', max_length=30)),
                ('status_confirmation', models.CharField(default='ausstehend', max_length=30)),
                ('status', models.CharField(blank=True, choices=[('VF', 'Verifiziert'), ('PE', 'in Bearbeitung'), ('AC', 'akzeptiert'), ('IQ', 'aktive Untersuchung'), ('RJ', 'Einfuhr abgelehnt')], default='PE', max_length=2)),
                ('custom_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_custom_officer', to='lucidapp.employee')),
                ('customs_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lucidapp.customsoffice')),
                ('document', models.ManyToManyField(blank=True, related_name='document', to='lucidapp.Document')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='lucidapp.transaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='lucidapp.invoice')),
            ],
        ),
    ]
